from configparser import ConfigParser

config = ConfigParser()
config.read("./conf.ini")

TOKEN = config["BOT"]["TOKEN"]

BASE_WEBHOOK_URL = config["SERVER"]["BASE_WEBHOOK_URL"]

DB_HOST = config["DATABASE"]["HOST"]
DB_PORT = config["DATABASE"]["PORT"]
DB_USERNAME = config["DATABASE"]["USERNAME"]
DB_PASSWORD = config["DATABASE"]["PASSWORD"]
DB_DATABASE = config["DATABASE"]["DATABASE"]

DB_PRODUCTS_TABLE = config["DATABASE"]["PRODUCTS_TABLE"]
DB_SENT_TO_ADMIN_TABLE = config["DATABASE"]["SENT_TO_ADMIN_TABLE"]
DB_CATEGORIES_TABLE = config["DATABASE"]["CATEGORIES_TABLE"]

SUPER_ADMIN_CHAT_ID = config["BOT"]["SUPER_ADMIN_CHAT_ID"]
